name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    #environment: ${{ github.ref == 'main' && 'production' || 'staging' }}
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_HUB_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_USER }}/${{ vars.DOCKER_HUB_APPNAME }}
      BRANCH: ${{ github.ref_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: Build & Push Docker Image
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:$BRANCH .
          docker push $DOCKER_HUB_REPOSITORY:$BRANCH
          if [ "$BRANCH" == "main" ]; then
            docker tag $DOCKER_HUB_REPOSITORY:$BRANCH $DOCKER_HUB_REPOSITORY:latest
            docker push $DOCKER_HUB_REPOSITORY:latest
          fi

  deploy:
    needs: build  # Deploy only after successful build
    runs-on: ubuntu-latest
    #environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_HUB_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_USER }}/${{ vars.DOCKER_HUB_APPNAME }}
      DOCKER_HUB_APPNAME: ${{ vars.DOCKER_HUB_APPNAME }}
      DOCKER_TAG: ${{ github.ref_name }}
    steps:
      - name: SSH into Server & Deploy to Docker Swarm
        uses: appleboy/ssh-action@master
        with:
          host: dev.atulatech.com
          port: 10022  # Use custom SSH port
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker pull $DOCKER_HUB_REPOSITORY:$DOCKER_TAG
            docker stack deploy -c docker-compose.${{github.repo}}.yml ${DOCKER_HUB_APPNAME}-stack
