name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_HUB_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_USER }}/${{ vars.DOCKER_HUB_APPNAME }}
      BRANCH: ${{ github.ref_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        
        run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

      - name: Build & Push Docker Image
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:$BRANCH .
          docker push $DOCKER_HUB_REPOSITORY:$BRANCH
          if [ "$BRANCH" == "main" ]; then
            docker tag $DOCKER_HUB_REPOSITORY:$BRANCH $DOCKER_HUB_REPOSITORY:latest
            docker push $DOCKER_HUB_REPOSITORY:latest
          fi
      - name: Upload Compose File (To Runner Host)
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artifacts
          path: |
            docker-compose.production.yml
            docker-compose.staging.yml
  deploy:
    needs: build  # Deploy only after successful build
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_HUB_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_USER }}/${{ vars.DOCKER_HUB_APPNAME }}
      DOCKER_HUB_APPNAME: ${{ vars.DOCKER_HUB_APPNAME }}
      DOCKER_TAG: ${{ github.ref_name }}
    steps:
      - name: Download Compose File (To Runner Host)
        uses: actions/download-artifact@v4
        with:
          name: deploy-artifacts
      - name: List files after artifact download
        run: pwd && ls -lR
      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          port: ${{ vars.DEPLOY_PORT }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            deploy-artifacts/docker-compose.production.yml
            deploy-artifacts/docker-compose.staging.yml
          target: ~/
      - name: SSH into Server & Deploy to Docker Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          port: ${{ vars.DEPLOY_PORT }}  # Use custom SSH port
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKER_REPOSITORY=${{ vars.DOCKER_HUB_USER }}/${{ vars.DOCKER_HUB_APPNAME }}
            export BUILD_TAG=${{ github.ref_name }}
            export BRANCH=$BUILD_TAG
            if [ "$BRANCH" = "main" ]; then
              export STACK_NAME=${{ vars.DOCKER_HUB_APPNAME }}-production
              export COMPOSE_FILE=docker-compose.production.yml
            elif [ "$BRANCH" = "develop" ]; then
              export STACK_NAME=${{ vars.DOCKER_HUB_APPNAME }}-staging
              export COMPOSE_FILE=docker-compose.staging.yml
            else
              export STACK_NAME=${{ vars.DOCKER_HUB_APPNAME }}-stack
              export COMPOSE_FILE=docker-compose.yml
            fi
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker pull $DOCKER_REPOSITORY:$BUILD_TAG
            docker stack deploy -c $COMPOSE_FILE $STACK_NAME
